// This file was generated by Prisma. It loads environment variables from `.env`
// so you don't need to `export` DATABASE_URL in the shell before running
// Prisma commands.
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    // Read DATABASE_URL from process.env (populated by dotenv)
    url: env("DATABASE_URL"),
  },
});
